config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.order("id DESC").paginate(:page => params[:page], :per_page => 10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end


  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :state, :zip, :description, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to @restaurant
    else
      flash[:notice] = "Please fill out correctly."
      render 'new'
    end
  end

  def review_params
    params.require(:review).permit(:rating, :body, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<%= link_to 'Submit Restaurant', new_restaurant_path %>

<h2>List of Restaurants</h2>

<table>
  <tr>
    <th>Name</th>
    <th>Adress</th>
    <th>City</th>
    <th>State</th>
  </tr>

  <% @restaurants.each do |restaurant| %>
    <tr>
      <td><%= restaurant.name %></td>
      <td><%= restaurant.address %></td>
      <td><%= restaurant.city %></td>
      <td><%= restaurant.state %></td>
      <td><%= link_to 'Show', restaurant_path(restaurant)  %></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @restaurants %>

app/views/restaurants/new.html.erb
<h2>Post New Restaurants</h2>

<%= form_for @restaurant do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </p>
  <p>
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>

Address: <%= @restaurant.address %><br>
City: <%= @restaurant.city %><br>
State: <%= @restaurant.state %><br>
Zip: <%= @restaurant.zip %><br><br>

<%= link_to 'Submit New Review', new_restaurant_review_path(@restaurant) %>

<h2>Reviews</h2>
<table>
  <tr>
    <th>Rating</th>
    <th>Review</th>
  </tr>
<% @reviews.each do |review|  %>
  <tr>
    <th><%= review.rating %></th>
    <th><%= review.body %></th>
  </tr>
<% end %>
</table>


<br><br>

<%= link_to 'See All Restaurants', restaurants_path %>

app/views/reviews/new.html.erb
<h2>Post Review</h2>

<%= form_for [@restaurant, @review] do |f| %>
  <p>
    <%= f.label :rating %><br>
    <%= f.text_field :rating %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>


<%= link_to 'Back to All Restaurants', restaurants_path %>